### ISSUE TITLE
Exception on first-time launch

### ISSUE THREAD

**Issue by sohocoke** [mamiksik/Desktop-Profiles#1]
Launching the app silently failed.

Got an error on running the app binary from a shell, suggesting some initial file system setup may be missing:
```
user1@host ~> /Users/user1/Downloads/DesktopProfiles.app/Contents/MacOS/DesktopProfiles
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/user1/Library/Group Containers/com.mamiksik.Maturitka/default.realm.management': make_dir() failed: No such file or directory." UserInfo={Error Code=2, NSFilePath=/Users/user1/Library/Group Containers/com.mamiksik.Maturitka/default.realm.management, Underlying=make_dir() failed: No such file or directory, NSLocalizedDescription=Unable to open a realm at path '/Users/user1/Library/Group Containers/com.mamiksik.Maturitka/default.realm.management': make_dir() failed: No such file or directory.}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.42/src/swift/stdlib/public/core/ErrorType.swift, line 184
[1]    45189 illegal hardware instruction  /Users/user1/Downloads/DesktopProfiles.app/Contents/MacOS/DesktopProfiles
user1@host ~>                                                                               
```

**Comment by mamiksik** [comment]
Thank you for reporting I will have a look into it.

**Comment by mamiksik** [comment]
@sohocoke Could you please confirm that attached version is not crashing? 
[DesktopProfiles.zip](https://github.com/mamiksik/Desktop-Profiles/files/2948265/DesktopProfiles.zip)

**Comment by sohocoke** [comment]
@mamiksik this one launches when run from shell so I can at least try it out. Opening it from the Finder (‘Open’ from the context menu, to override Gatekeeper settings) the still fails. I’d send you a log but Console is not showing anything for the app.

You could create a new user on your Mac and try downloading and running the app to see if you can reproduce the problem.

**Comment by mamiksik** [comment]
Hi, I created a test account and I think I have fixed all issues. There were some problems with write permission for realm. @sohocoke Could you please test this version? :) 
[DesktopProfiles.zip](https://github.com/mamiksik/Desktop-Profiles/files/2952895/DesktopProfiles.zip)
.

**Comment by sohocoke** [comment]
This one launches successfully from the Finder. Congratulations :)
