### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by DrLeucine** [mamiksik/Desktop-Profiles#4]
I can't install this app at all on Mac OS X 10.14.5

launching the app does nothing. Attached is the crash report. 

Am I missing something? 
[DesktopProfiles_2019-08-22-141027_univesvm.crash.zip](https://github.com/mamiksik/Desktop-Profiles/files/3530258/DesktopProfiles_2019-08-22-141027_univesvm.crash.zip)

**Comment by mamiksik** [comment]
Hi,
thank you for reporting this issue. I will have look into it ASAP.

**Comment by mamiksik** [comment]
Hi  @universvm,
I am sorry for late response. School and work have been priority for me in the past months. I have exported a new(and hopefully fixed) version of the app. Could you try opening it? 
[DesktopProfiles.zip](https://github.com/mamiksik/Desktop-Profiles/files/3720574/DesktopProfiles.zip)

**Comment by DrLeucine** [comment]
I get `“DesktopProfiles.app” is damaged and can’t be opened. You should move it to the Trash.`

**Comment by mamiksik** [comment]
Would it be possible for you to build the app from source on your machine?

**Comment by mamiksik** [comment]
http://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/
