### ISSUE TITLE
I've been looking for this app for years!

### ISSUE THREAD

**Issue by adamshand** [mamiksik/Desktop-Profiles#8]
Hey,

I've been hunting around for a window manager for years which will allow me to save configured states of apps as a workspace.

Having discovered Desktop-Profiles, I'm sad to see that it looks like it is no longer being maintained.  

I'm wondering if you found another tool to do this?

Thanks,
Adam.

**Comment by elisavetsky** [comment]
@adamshand I think you're looking for [Workspaces 2](https://www.apptorium.com/workspaces)

**Comment by adamshand** [comment]
Thank you, having a look!
